@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle rectangle

"push" -> "ZenML Develop Workflow"

package "ZenML Develop Workflow" {
 runner -> [Checkout]
 [Checkout] -> [Setup]
 [Setup] -> [Install Requirements]
 [Install Requirements] --> [Run ZenML Flow]
 [Run ZenML Flow] ->[Upload Model]
[Upload Model] -> [Run Automated Tests]
[Run Automated Tests] -> [CleanUp]
}
storage model_store[
    <i>Model Storage
....
ML models uploaded as artifacts
]



[Upload Model] -- model_store


@enduml