@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle rectangle

"push" -> "ZenML Develop Workflow"

package "ZenML Develop Workflow" {
 runner -> [Checkout]
 [Checkout] -> [Setup]
 [Setup] -> [Install Requirements]
 [Install Requirements] --> [Run Automated Tests]
 [Run Automated Tests] -> [Run ZenML Flow]
[Run ZenML Flow] -> [Upload Model]
}
storage model_store[
    <i>Model Storage
....
ML models uploaded as artifacts
]



[Upload Model] -- model_store


@enduml