@startuml
'https://plantuml.com/component-diagram

skinparam rectangle {
    roundCorner<<"">> 25
}

rectangle "French Road Accident Unified Decision Maker" <<FRAUD>>{
database "Input" {
file RoadAccidentData <<parquet>>
}
package "ZenML Machine Learning Module" {
[Data Loader] => [Data Processor]
[Data Processor] => [Train Forecast]
[Data Processor] -> [Data DriftMonitor]
[Data Processor] --> [Train Classifier]
[Data Processor] -- [Log DataSet]
[Train Forecast] -> [Log Model]
[Train Classifier] --> [Log Model]
}

package "Neptune AI"{
Collections "Severity Classifier Runs" <<version>>
Collections "Forecaster Runs" <<version>>
}
package "Evidently Monitoring"{
Collections "Data Drift Monitor" <<run>>
Collections "ForecastModel Drift Monitor" <<run>>
Collections "SeverityModel Drift Monitor" <<run>>
}

cloud "Comet ML"{
database "Input Data"<<parquet>>{
}
Collections "Severity Classifier.pkl" <<version>>
Collections "Forecaster.pkl" <<version>>
}


'Connections
"RoadAccidentData" => "ZenML Machine Learning Module"
"Log Model" -- "Comet ML"
"Log DataSet" - "Input Data"
"ZenML Machine Learning Module" ..> "Neptune AI"
"ZenML Machine Learning Module" ..> "Evidently Monitoring"



@enduml