@startuml
'https://plantuml.com/component-diagram

skinparam rectangle {
    roundCorner<<"">> 25
}

rectangle "French Road Accident Unified Decision Maker" <<FRAUD>>{
database "Input" {
file RoadAccidentData <<parquet>>
}
package "ZenML Machine Learning Module" {
[Data Loader] => [Data Processor]
[Data Processor] => [Train Forecast]
[Data Processor] -> [Data DriftMonitor]
[Data Processor] --> [Train Classifier]
[Data Processor] -- [Log DataSet]
[Train Forecast] -> [Log Model]
[Train Classifier] --> [Log Model]
}

package "Neptune AI"{
Collections "Severity Classifier Runs" <<version>>
Collections "Forecaster Runs" <<version>>
}
package "Evidently Monitoring"{
Collections "Data Drift Monitor" <<run>>
Collections "ForecastModel Drift Monitor" <<run>>
Collections "SeverityModel Drift Monitor" <<run>>
}

cloud "Comet ML"{
database "Input Data"<<parquet>>{
}
Collections "Severity Classifier.pkl" <<version>>
Collections "Forecaster.pkl" <<version>>
}


'Connections
"RoadAccidentData" => "ZenML Machine Learning Module"
"Log Model" -- "Comet ML"
"Log DataSet" - "Input Data"
"ZenML Machine Learning Module" ..> "Neptune AI"
"ZenML Machine Learning Module" ..> "Evidently Monitoring"

package "RoadAccident Service"{
rectangle "DockerContainers"{
component "FAST API Inference Point"{
node "predict/forecast" <<ForecastRequest>>
node "/predict/severity" <<SeverityRequest>>
node "POST Retrain" <<AdminRequest>>
node "StartUpService" <<get_models>>
json ForecastRequest{
"Periods" : "Number of Periods"
}
json SeverityRequest{
"Location" : "Location of the Accident ",
"Vehicle Category" : "Category of Vehicle"
}
json AdminRequest{
"Retrain" : "Retraining Trigger"
}
json ForecastResponse{
"status" : "Status",
"[Accidents Response]" : "Number of Accidents"
}
json SeverityResponse{
"status" : "Status",
"Severity" : "Major or Minor Accident"
}
"predict/forecast"  .. "ForecastRequest"
"predict/forecast"  .. "ForecastResponse"
"/predict/severity" ..  "SeverityRequest"
"/predict/severity" ..  "SeverityResponse"
"POST Retrain" .. "AdminRequest"

}
rectangle "OpenAPI Endpoint" <<fast_api:8000/docs>>
}
rectangle "Docker Test User"{
component "User Test Client"
}

rectangle "Docker Test Admin"{
component "Admin Test Client"
}
rectangle "Docker Prometheus"{
component "Prometheus Instrumentation" <<fast_api:9090>>
}
rectangle "Docker Grafana"{
component "Grafana Dashboard" <<fast_api:3000>>
}
actor Human

'Connections
"Human" -- "OpenAPI Endpoint" : REST
"Docker Prometheus" . "FAST API Inference Point" : METRICS
"Docker Grafana" .. "FAST API Inference Point"
"FAST API Inference Point" == "Docker Test Admin": POST<<AdminRequest>>
"Docker Test User" -- "FAST API Inference Point" : GET<<ForecastResponse>>
"StartUpService" -- "Comet ML"
}
}


@enduml
