#https://docs.docker.com/compose/intro/compose-application-model/
##https://github.com/Kludex/fastapi-prometheus-grafana/blob/master/docker-compose.yaml
services:
  fast_api:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: fast_api_container
    ports:
      - "8000:8000"
    networks:
      - test_network

  docker_1_test:
    build:
      context: .
      dockerfile: Dockerfile_docker_1
    container_name: docker_1_test_container
    networks:
      - test_network
    depends_on:
      - fast_api

  docker_2_test:
    build:
      context: .
      dockerfile: Dockerfile_docker_2
    container_name: docker_2_test_container
    networks:
      - test_network
    depends_on:
      - fast_api

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - test_network
    depends_on:
      - fast_api

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - test_network
    depends_on:
      - prometheus


networks:
  test_network:

