##Docker File for the Admin user
#https://fastapi.tiangolo.com/deployment/docker/#build-the-docker-image
FROM python:3.9
WORKDIR /code
COPY requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

##Should copy the entire app folder as that is what I care about
COPY . /code/app
#COPY ./docker_1_test.py /code/
#COPY ./docker_2_test.py /code/
#COPY ./docker_3_test.py /code/
#COPY ./utils.py /code/
EXPOSE 8000
##RUN the ADNMIN
CMD ["python", "app/docker_1_test.py"]

