name: Deploy ZenM flow

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Test ZenML
        run: |
          pip install -r requirements.txt
          python test-zenml.py
