name: Deploy ZenM flow

on:
  push:
    branches: [ "test-runner-ci" ]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: |
          echo "Installing requirements..."
          pip install -r requirements.txt
          echo "Requirements installation completed."

      - name: Test ZenML
        run: |
          echo "Running tests..."
          python test-zenml.py
          echo "Tests completed."

      - name: Upload Log Files
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs
          path: ${{ github.workspace }}/logs/*.log
          retention-days: 10

      - name: Cleanup Runner
        uses: eviden-actions/clean-self-hosted-runner@v1
        if: always()