name: Deploy ZenM flow

on:
  push:
    branches: ["test-2"]
jobs:
  deploy:
    name: Deploy Test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: |
          python test-zenml.py
      - uses: actions/upload-artifact@v4
        with:
          name: test-alt
          path: ${{ github.workspace }}/**/*.png
      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: always()