name: Deploy ZenM flow

on:
  push:
    branches: ["test-runner-ci"]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: |
          echo "Installing requirements..."
          pip install -r requirements.txt
          echo "Requirements installation completed."

      - name: Test and Upload ZenML Logs
        run: |
          echo "Running Zen ML"
          python test-zenml.py
          echo "Zen ML Complete."

      - name: Verify Logs Directory
        run: |
          echo "Checking logs directory contents:"
          ls -la ${{ github.workspace }}/../logs

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs
          path: ${{ github.workspace }}/../logs/**/*.log
          retention-days: 10
          compression-level: 3