[mapbox]
# Configure Streamlit to use a custom Mapbox
# token for elements like st.pydeck_chart and st.map.
# To get a token for yourself, create an account at
# https://mapbox.com. It's free (for moderate usage levels)!
# Default: ""
token = "sk.eyJ1IjoiZnJhbi10ZXN0LTMiLCJhIjoiY202eHRxb3V0MHhnejJsc2Mxa2liNHNiciJ9.87XPNXJKh50tTt1xLugvAA"

[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 250

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 250

# Enables support for websocket compression.
# Default: false
enableWebsocketCompression = true